set_property IOSTANDARD LVCMOS33 [get_ports uart_rx_i]
set_property IOSTANDARD LVCMOS33 [get_ports ENA]
set_property IOSTANDARD LVCMOS33 [get_ports ENB]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx_o]
set_property IOSTANDARD LVCMOS33 [get_ports IN1]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n_i]
set_property IOSTANDARD LVCMOS33 [get_ports IN2]
set_property IOSTANDARD LVCMOS33 [get_ports IN3]
set_property IOSTANDARD LVCMOS33 [get_ports IN4]
set_property PACKAGE_PIN N14 [get_ports uart_rx_i]
set_property PACKAGE_PIN M14 [get_ports uart_tx_o]
set_property PACKAGE_PIN C4 [get_ports IN1]
set_property PACKAGE_PIN B13 [get_ports IN2]
set_property PACKAGE_PIN N10 [get_ports IN3]
set_property PACKAGE_PIN M10 [get_ports IN4]
set_property PACKAGE_PIN B14 [get_ports ENA]
set_property PACKAGE_PIN D3 [get_ports ENB]
set_property PACKAGE_PIN C3 [get_ports rst_n_i]
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS33} [get_ports clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]


set_property PACKAGE_PIN J1 [get_ports LED1]
set_property PACKAGE_PIN A13 [get_ports LED2]
set_property IOSTANDARD LVCMOS33 [get_ports LED2]
set_property IOSTANDARD LVCMOS33 [get_ports LED1]
set_property DRIVE 12 [get_ports LED1]
set_property SLEW SLOW [get_ports LED1]
set_property PULLDOWN true [get_ports LED1]
set_property PULLDOWN true [get_ports LED2]
